Blog/blog_proyecto/blog_proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('api/', include('rest_blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog/blog_proyecto/core/urls.py
from django.urls import path
from core.views import *
from . import views
from django.contrib.auth import views as auth_views
from .forms import UserPasswordResetForm, SetPasswordFormForm

urlpatterns = [
    path('', views.index, name='index'),
    path('perfil/<str:pk>/', views.perfil, name='perfil'),
    path('editar-perfil/<int:pk>/', PerfilUpdateView.as_view(), name='editar-perfil'),
    path('publicaciones/', views.publicaciones, name='publicaciones'),
    path('publicacion/<str:pk>/', views.publicacion, name='publicacion'),
    path('donacion/', views.donacion, name='donacion'),
    path('logearse/', views.logearse, name='logearse'),
    path('registrarse/', views.registrarse, name='registrarse'),
    path('cerrar-sesion/', views.cerrar_sesion, name='cerrar-sesion'),
    path('nueva-publicacion/', views.nueva_publicacion, name='nueva-publicacion'),
    path('editar-publicacion/<str:pk>/', views.editar_publicacion, name='editar-publicacion'),
    path('eliminar-publicacion/<str:pk>/', views.eliminar_publicacion, name='eliminar-publicacion'),
    path('like-index/<str:pk>/', views.likes_index, name='like-index'),
    path('like-publicacion/<str:pk>/', views.likes_publicacion, name='like-publicacion'),
    path('like-publicaciones/<str:pk>/', views.likes_publicaciones, name='like-publicaciones'),
    path('panel-admin/', views.panel_administracion, name='panel-admin'),
    path('editar-comentario/<str:pk>/', views.editar_comentario, name='editar-comentario'),
    path('eliminar-comentario/<str:pk>/', views.eliminar_comentario, name='eliminar-comentario'),
    
    #Recuperar contrasena, solo sirve localmente
    path('recuperar-contrasena/',
        auth_views.PasswordResetView.as_view(
        template_name='core/recuperar-contrasena.html',
        form_class=UserPasswordResetForm,
        email_template_name='core/password_reset_email.html',
        subject_template_name='core/password_reset_subject.txt'),
        name="recuperar-contrasena"),
    
    path('recuperar-contrasena-enviado/',
        auth_views.PasswordResetDoneView.as_view(
        template_name='core/recuperar-contrasena-enviado.html'),
        name='password_reset_done'),
    
    path('recuperar/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
        template_name='core/recuperar-contrasena-formulario.html',
        form_class=SetPasswordFormForm),
        name="password_reset_confirm"),
    
    path('recuperar-contrasena-completo/',
        auth_views.PasswordResetCompleteView.as_view(
        template_name='core/logearse.html'),
        name='password_reset_complete')
    
]

Blog/blog_proyecto/core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
    imagen = models.ImageField(default='default.jpg')
    biografia = models.TextField()
    genero = models.CharField(
        max_length=50,
        choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')]
    )
    rol = models.CharField(
        max_length=50,
        choices=[('Admin', 'Admin'), ('Lector', 'Lector')],
        default='Lector'
    )

    username = models.CharField(max_length=150, unique=True)
    email = models.EmailField(unique=True)
    fecha_registro = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.username


class Publicacion(models.Model):
    autor = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=100)
    categoria = models.ForeignKey('Categoria', on_delete=models.CASCADE)
    imagen = models.ImageField(default=None)
    texto = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(Usuario, related_name='blog_publicaciones', blank=True)
    estatus = models.BooleanField(default=True)

    def __str__(self):
        return self.titulo

class Categoria(models.Model):
    nombre = models.CharField(max_length=30)
    imagen = models.ImageField(default=None)
    
    def __str__(self):
        return self.nombre

class Comentario(models.Model):
    autor = models.ForeignKey(Usuario, related_name='usuario', on_delete=models.CASCADE, default=None)
    publicacion = models.ForeignKey(Publicacion, related_name='comentarios', on_delete=models.CASCADE)
    texto = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    estatus = models.BooleanField(default=True)
    
    def __str__(self):
        return self.texto

Blog/blog_proyecto/core/forms.py
from django import forms
from django.forms import ModelForm
from .models import Comentario, Publicacion
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario
from django.contrib.auth import views
import re
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm
    
class PublicacionForm(ModelForm):
    class Meta:
        model = Publicacion
        fields = ['titulo', 'categoria','texto', 'imagen']
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Ingresa un titulo'}),
            'categoria': forms.Select(attrs={'class': 'form-control'}),
            'imagen': forms.FileInput(attrs={'class': 'form-control'}),
            'texto': forms.Textarea(attrs={'class': 'form-control', 'placeholder':'Ingresa el cuerpo de tu publicacion'})
        }

class CrearUsuarioFormulario(UserCreationForm):
    
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password', 'placeholder':'**********'}),
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password', 'placeholder':'**********'})
    )
    
    class Meta:
        model = Usuario
        fields = ['username', 'email']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'nombre'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder':'correo@ejemplo.com', 'id':'floatingTextarea2'})
        }
        
class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['texto']
        widgets = {
            'texto': forms.TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder':'Añade un comentario...'}),
        }
        
class EditarPerfilForm(forms.ModelForm):
    
    class Meta:
        model = Usuario
        fields = ['username', 'email', 'imagen', 'biografia', 'genero']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'imagen': forms.FileInput(attrs={'class': 'form-control'}),
            'biografia': forms.Textarea(attrs={'class': 'form-control'}),
            'genero': forms.Select(attrs={'class': 'form-control'}),
        }
        
    def clean_username(self):
        username = self.cleaned_data.get('username')
        pattern = r'^[a-zA-Z0-9]+$'  # Expresión regular para permitir solo letras mayúsculas, minúsculas y números
        if not re.match(pattern, username):
            raise forms.ValidationError('El nombre de usuario solo puede contener letras y números. SIN ESPACIOS')
        return username
    
class UserPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(UserPasswordResetForm, self).__init__(*args, **kwargs)

    email = forms.EmailField(label='', widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Ingresa tu correo',
        'type': 'email',
        'name': 'email'
        }))
    
class SetPasswordFormForm(SetPasswordForm):

    new_password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password', 'placeholder':'**********'}),

    )
    new_password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password', 'placeholder':'**********'}),
    )

Blog/blog_proyecto/core/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy, reverse
from .models import *
from .forms import PublicacionForm, CrearUsuarioFormulario, ComentarioForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator
from django.views.generic.edit import UpdateView 
from django.contrib.auth.models import User
from .forms import EditarPerfilForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

def index(request):
    publicaciones = Publicacion.objects.order_by('-fecha_creacion')[:3]
    categorias = Categoria.objects.all()

    context = {'publicaciones':publicaciones, 'categorias':categorias}
    return render(request, 'core/index.html', context)

def publicaciones(request):
    pagina = Paginator(Publicacion.objects.all(), 3)
    pagina_numero = request.GET.get('pagina')
    pagina_objeto = pagina.get_page(pagina_numero)  
    
    request.session['pagina_numero'] = pagina_numero
    context = {'publicaciones':pagina_objeto}
    
    return render(request, 'core/publicaciones.html', context)

def publicacion(request, pk):
    publicacion = Publicacion.objects.get(id=pk)
    formulario_comentario = ComentarioForm()

    if request.method == 'POST':
        formulario_comentario = ComentarioForm(request.POST)
        if formulario_comentario.is_valid():
            comentario = formulario_comentario.save(commit=False)
            comentario.autor = Usuario.objects.get(username=request.user)
            comentario.publicacion = Publicacion.objects.get(id=pk)
            
            formulario_comentario.save()
            return HttpResponseRedirect(reverse('publicacion', args=[str(pk)]))

    context = {'publicacion':publicacion, 'formulario_comentario':formulario_comentario}
    return render(request, 'core/publicacion.html', context)

#Sistema de likes
@login_required
def likes_index(request, pk):
    publicacion = get_object_or_404(Publicacion, id=request.POST.get('publicacion-index-id'))
    
    if publicacion.likes.filter(id=request.user.id).exists():
        publicacion.likes.remove(request.user)
    else:
        publicacion.likes.add(request.user)
        
    return HttpResponseRedirect(reverse('index'))

@login_required
def likes_publicaciones(request, pk):
    publicacion = get_object_or_404(Publicacion, id=request.POST.get('publicaciones-id'))

    if publicacion.likes.filter(id = request.user.id).exists():
        publicacion.likes.remove(request.user)
    else:
        publicacion.likes.add(request.user)
        
    pagina_numero = request.session.get('pagina_numero', '')
    url_redireccion = reverse('publicaciones') + f'?pagina={pagina_numero}'

    return HttpResponseRedirect(url_redireccion)   

@login_required
def likes_publicacion(request, pk):
    publicacion = get_object_or_404(Publicacion, id=request.POST.get('publicacion-id'))
    
    if publicacion.likes.filter(id = request.user.id).exists():
        publicacion.likes.remove(request.user)
    else:
        publicacion.likes.add(request.user)
        
    return HttpResponseRedirect(reverse('publicacion', args=[str(pk)]))

@user_passes_test(lambda user: user.is_staff, login_url=reverse_lazy('index'))
def panel_administracion(request):
    publicaciones = Publicacion.objects.all()
    comentarios = Comentario.objects.all()
    usuarios = Usuario.objects.all()
    
    
    context = {'publicaciones':publicaciones,'comentarios':comentarios,'usuarios':usuarios}
    return render(request, 'core/panel-admin.html', context)

def donacion(request):
    return render(request, 'core/donacion.html')

@user_passes_test(lambda user: user.is_staff, login_url=reverse_lazy('index'))
def nueva_publicacion(request):
    formulario = PublicacionForm()

    if request.method == 'POST':
        formulario = PublicacionForm(request.POST, request.FILES)
        if formulario.is_valid():
            publicacion = formulario.save(commit=False)
            publicacion.autor = Usuario.objects.get(username=request.user)

            formulario.save()
            return redirect('panel-admin')
        
    context = {'form': formulario}
    return render(request, 'core/nueva-publicacion.html', context)

@user_passes_test(lambda user: user.is_staff, login_url=reverse_lazy('index'))
def editar_publicacion(request, pk):
    publicacion = Publicacion.objects.get(id=pk)
    form = PublicacionForm(instance=publicacion)

    if request.method == 'POST':
        form = PublicacionForm(request.POST, request.FILES, instance=publicacion)
        if form.is_valid():
            form.save()
            return redirect('panel-admin')

    context = {'form': form}
    return render(request, 'core/editar-publicacion.html', context)

@user_passes_test(lambda user: user.is_staff, login_url=reverse_lazy('index'))
def eliminar_publicacion(request, pk):
    
    publicacion = Publicacion.objects.get(id=pk)
    if request.method == 'POST':
        
        publicacion.delete()
        return redirect('panel-admin')

    context = {'publicacion': publicacion}
    return render(request, 'core/eliminar-publicacion.html', context)

def registrarse(request):
    formulario = CrearUsuarioFormulario()
    
    if request.method == 'POST':
        formulario = CrearUsuarioFormulario(request.POST)
        if formulario.is_valid():
            formulario.save()
            usuario = formulario.cleaned_data.get('username')
            
            messages.success(request, 'La cuenta fue creada para' + ' ' + usuario)
            return redirect('logearse')
        else:
            messages.info(request, 'Nombre o correo ya existente')

    context = {'form':formulario}
    return render(request, 'core/registrarse.html', context)

def logearse(request):
    if request.method == 'POST':
        usuario = request.POST.get('nombre')
        contrasena = request.POST.get('contrasena')
        
        user = authenticate(request, username=usuario, password=contrasena)
        
        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            messages.info(request, 'Usuario o contraseña es incorrecto')

    return render(request, 'core/logearse.html')

def cerrar_sesion(request):
    logout(request)
    return redirect('logearse')

def perfil(request, pk):
    usuario = Usuario.objects.get(id=pk)
    comentarios = Comentario.objects.filter(autor=usuario)
    publicaciones = Publicacion.objects.filter(autor=usuario)
    
    context = {'usuario':usuario, 'publicaciones':publicaciones, 'comentarios':comentarios}
    return render(request, 'core/perfil.html', context)


#---Editar Perfil
class PerfilUpdateView(LoginRequiredMixin, UpdateView):
    model = Usuario
    form_class = EditarPerfilForm
    template_name = 'core/editar-perfil.html'
    
    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated and self.request.user.pk == self.kwargs['pk']:
            return super().dispatch(request, *args, **kwargs)
        else:
            return redirect('index')

    def get_success_url(self):
        return reverse_lazy('perfil', kwargs={'pk': self.kwargs['pk']})

@user_passes_test(lambda user: user.is_staff, login_url=reverse_lazy('index'))
def editar_comentario(request, pk):
    comentario = Comentario.objects.get(id=pk)
    form = ComentarioForm(instance=comentario)

    if request.method == 'POST':
        form = ComentarioForm(request.POST, instance=comentario)
        if form.is_valid():
            form.save()
            return redirect('panel-admin')

    context = {'form': form, 'comentario':comentario}
    return render(request, 'core/editar-comentario.html', context)

@user_passes_test(lambda user: user.is_staff, login_url=reverse_lazy('index'))
def eliminar_comentario(request, pk):
    comentario = Comentario.objects.get(id=pk)
    if request.method == 'POST':
        
        comentario.delete()
        return redirect('panel-admin')

    context = {'comentario': comentario}
    return render(request, 'core/eliminar-comentario.html', context)

Blog/blog_proyecto/core/templates/core/donacion.html
<!doctype html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">   
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
     <!-- Incluye la librería de JQuery 3.6.4 -->
     <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
     <!-- Incluye el archivo de validación de formulario -->
     <script src="../js/donacion_validacion.js"></script>

  </head>

<body style="background-color: #e9ecef;">

  {% include 'core/barra-navegacion.html' %}
    
<main class="container shadow-sm" style="background-color: #f8f9fa; ">
  <br>
  <h2>Formulario de donación para nuestro blog</h2>
  <form id="donacionForm">
    <div class="mb-3" style="padding-top: 20px;">
        <label for="nombre" class="form-label">Nombre</label>
        <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Ingrese su nombre" required>
      </div>
      <label for="email">Correo electrónico:</label>
      <br>
      <input type="email" class="form-control" id="email" name="email" placeholder="Ingrese su correo electrónico" required>
      <div class="mb-3"><br>
        <label for="monto" class="form-label">Monto de la donación</label>
        <input type="number" class="form-control" id="monto" name="monto" min="1" max="999999999" placeholder="Digite un monto" required>
      </div>
      <label for="pago">Método de pago:</label>
      <select id="pago" name="pago" class="form-select">
        <option value="">Seleccione un método</option>
        <option value="tarjeta">Tarjeta de crédito</option>
        <option value="paypal">PayPal</option>
        <option value="transferencia">Transferencia bancaria</option>
      </select>      
      <br>
      <div class="mb-3">
        <label for="mensaje" class="form-label">Mensaje (opcional)</label>
        <textarea class="form-control" id="mensaje" name="mensaje" rows="4" placeholder="Escríbenos un mensaje"></textarea>
    </div>

    <div class="d-grid gap-2 col-6 mx-auto">
      <button class="btn btn-primary" type="submit">Donar <i class="bi bi-heart"></i></button>
    </div>

    <div id="errores" style="color: red;"></div>
    <div id="gracias-mensaje" style="display: none;">¡Gracias por tu donación!</div>
    </form>

    {% include 'core/footer.html' %}
  
  </main>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</html>

Blog/blog_proyecto/core/templates/core/editar-comentario.html
<!doctype html>
<html lang="en">
  {% load static %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Blog</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
  <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
</head>

<body style="background-color: #e9ecef;">

  <style>
    label.error {
      color: red;
    }
    
  </style>

  {% include 'core/barra-navegacion.html' %}

  <main class="container shadow-sm" style="background-color: #f8f9fa; ">

    <div style="padding-top: 20px;">
      <h2 style="text-align: center;">Editar comentario de {{comentario.autor}}</h2>
    </div>
    
    <form method='POST'>
        {% csrf_token %}
    {{form.as_p}}
    <button class="btn btn-primary" type="submit">Editar</button>
    </form>

    {% include 'core/footer.html' %}

  </main>
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js" integrity="sha512-pumBsjNRGGqkPzKHndZMaAG+bir374sORyzM3uulLV14lN5LyykqNk8eEeUlUkB3U0M4FApyaHraT65ihJhDpQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js" integrity="sha512-rstIgDs0xPgmG6RX1Aba4KV5cWJbAMcvRCVmglpam9SoHZiUCyQVDdH2LPlxoHtrv17XWblE/V/PP+Tr04hbtA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="/js/publicacion-validacion.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</html>

Blog/blog_proyecto/core/templates/core/editar-perfil.html
{% load static %}

<!doctype html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Blog</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
  <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">   
  <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
</head>

<body style="background-color: #e9ecef;">

  {% include 'core/barra-navegacion.html' %}
  <main class="container shadow-sm" style="background-color: #f8f9fa; ">

    <h3 class="text-center" style="padding-top: 20px;">Editar perfil</h3>      
    <div class="ms-3"style="padding-top: 20px;">
    
      {% if request.user == usuario %}
      <form method="POST" enctype="multipart/form-data" action="{% url 'editar-perfil' usuario.pk %}">
        {% csrf_token %}
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success" role="alert">
          {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-danger" role="alert">
          <strong>{{ field.label }}</strong>: {{ error }}
        </div>
        {% endfor %}
        {% endfor %}
        {% endif %}

        <div class="mb-3">
          <label for="id_username" class="form-label">Nombre de usuario</label>
          {{ form.username }}
          {% if form.username.errors %}
          {% for error in form.username.errors %}
          <div class="alert alert-danger" role="alert">
            {{ error }}
          </div>
          {% endfor %}
          {% endif %}
        </div>

        <div class="mb-3">
          <label for="id_username" class="form-label">Correo</label>
          {{ form.email }}
          {% if form.email.errors %}
          {% for error in form.email.errors %}
          <div class="alert alert-danger" role="alert">
            {{ error }}
          </div>
          {% endfor %}
          {% endif %}
        </div>
        
        <div class="mb-3">
          <label for="id_imagen" class="form-label">Imagen</label>
          {{ form.imagen }}
          {% if form.imagen.errors %}
          {% for error in form.imagen.errors %}
          <div class="alert alert-danger" role="alert">
            {{ error }}
          </div>
          {% endfor %}
          {% endif %}
        </div>
        <div class="mb-3">
          <label for="id_biografia" class="form-label">Biografía</label>
          {{ form.biografia }}
          {% if form.biografia.errors %}
          {% for error in form.biografia.errors %}
          <div class="alert alert-danger" role="alert">
            {{ error }}
          </div>
          {% endfor %}
          {% endif %}
        </div>
        <div class="mb-3">
          <label for="id_genero" class="form-label">Género</label>
          {{ form.genero }}
          {% if form.genero.errors %}
          {% for error in form.genero.errors %}
          <div class="alert alert-danger" role="alert">
            {{ error }}
          </div>
          {% endfor %}
          {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">Guardar cambios</button>
        <a href="{% url 'perfil' usuario.id %}" class="btn btn-danger">Cancelar</a>
      </form>
      
      {% endif %}
    </div>
    
  </div>

  {% include 'core/footer.html' %}
  </main>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</html>